### ISSUE TITLE
Create Cluster Setup ARM template

### ISSUE THREAD

**Issue by rossf7** [giantswarm/azure-operator#7]
Towards giantswarm/sap-hybris#3

## Overview

This ARM template will create Azure resources that will be used by later ARM templates.

## Resources

So far the following resources have been identified.

### Storage Account

A [storage account](https://docs.microsoft.com/en-us/azure/storage/common/storage-create-storage-account) will be created per guest cluster. This will be used for Blob Storage and VM Disks.

### Key Vault

A Key Vault will be created per guest cluster for storing certificate files. On startup nodes will download the secrets from Key Vault via a systemd unit.

**Comment by rossf7** [comment]
# Tasks

- [x] Storage Account
- [ ] Key Vault
- [ ] Add Key Vault secret per certificate file
- [ ] Create Service Principal per guest cluster and grant read access to Key Vault
- [ ] Add systemd unit for downloading cert files from Key Vault

**Comment by rossf7** [comment]
Tested MSI (Managed Service Identities) on a CoreOS node in 'westeurope' region. It adds an Azure agent which has a local endpoint for retrieving OAuth tokens.

Docs for using MSI to access Key Vault on Linux.
https://docs.microsoft.com/en-us/azure/active-directory/msi-tutorial-linux-vm-access-nonaad

This example ARM template shows how to add the extension.
https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-msi-linux/azuredeploy.json#L361

**Comment by rossf7** [comment]
Changes to add secrets are done. Issue can be closed once #26 is merged.
